apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
  namespace: litecoin
  labels:
    app: litecoin
spec:
  selector:
    matchLabels:
      app: litecoin
  serviceName: "litecoin"
  replicas: 2
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: litecoin
        image: litecoin:0.18.1
        resources:
          requests:
            cpu: 800m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 4Gi
        ports:
        - containerPort: 9333
        volumeMounts:
        - name: litecoin-storage
          mountPath: /litecoin-data
  volumeClaimTemplates:
  - metadata:
      name: litecoin-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi